### ISSUE TITLE
[Soyoung] Udacity homework

### ISSUE THREAD

**Issue by conductor-tutti** [conductor-tutti/tutti#10]
Intro to Computer Science
Lesson 1, Problem Set까지 모두 들으세요.

**Comment by ghost** [comment]
쪼아염

**Comment by JuneSeok** [comment]
저도 보도록 하겠습니다.
실력을 많이 키워야 겠어요
지금 이대로는 ㅜ.ㅜ ㅋㅋ

**Comment by conductor-tutti** [comment]
@JuneSeok 준석이 경우에는 Udacity에서 Web development 강의 들어요. 더 도움 될거에요. 내 계정으로 들어가보면 있어요.

**Comment by conductor-tutti** [comment]
@alwayssayyes 학습 진행 상황을 코멘트로 달아주세요~

**Comment by conductor-tutti** [comment]
@alwayssayyes 본 이슈에서 할당한 만큼은 멋지게 해낸 것으로 압니다. 그 다음부터는 본인의 스케줄을 잘 조정하여, 알아서 잘 해나가길 바랍니다. 11월 첫 번째 주까지 적어도 Intro to Computer Science의 2/3 이상을 수강하기 바랍니다. 학습 중 어려운 부분이 있으면 언제든지 이슈에 올려주길 바랍니다. 화이팅 :)

**Comment by ghost** [comment]
좋아요! 차근차근 다른책도 함께 공부해가고 있습니다!

**Comment by conductor-tutti** [comment]
훈늉하군요?
