### ISSUE TITLE
[GitHub] Atlassian GitHub Tutorial 공부 및 실습

### ISSUE THREAD

**Issue by conductor-tutti** [conductor-tutti/tutti#11]
모두 내가 보내준 https://www.atlassian.com/git/tutorials/ 이 튜토리얼 잘 보고 있지요?
오늘까지 Getting Started 읽어오고 실습하는게 숙제였습니다.

읽기만 하고 직접 Shell에서 실습은 안한 것 같은데 시간 나면 간단하게라도 GitHub Shell을 사용해서 해보세요.
또한 내일 모레까지 Collaborating 파트까지 읽어오세요.

**Comment by ohtangza** [comment]
네!

2014-10-01 19:20 GMT+09:00 Seulkiming notifications@github.com:

> 모두 내가 보내준 https://www.atlassian.com/git/tutorials/ 이 튜토리얼 잘 보고 있지요?
> 오늘까지 Getting Started 읽어오고 실습하는게 숙제였습니다.
> 
> 읽기만 하고 직접 Shell에서 실습은 안한 것 같은데 시간 나면 간단하게라도 GitHub Shell을 사용해서 해보세요.
> 또한 내일 모레까지 Collaborating 파트까지 읽어오세요.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/conductor-tutti/tutti/issues/11.

## 

Jeungmin Oh, Ph.D Student,
Department of Knowledge Service Engineering, KAIST
+82 - 10 - 2711 - 1357

**Comment by ghost** [comment]
네!네! 네네네!

**Comment by JuneSeok** [comment]
실습 해보고 있습니다 ㅎㅎㅎㅎ

**Comment by conductor-tutti** [comment]
잘 되고 있나여? 전 SourceTree보다 Shell이 훨씬 편하던데.. 여러분 느낌은 어떤지..
GUI가 비쥬얼적으로는 쉬워보이는데, 동작 방식을 모르면 무용지물인 듯 하여요.
ㅋㅋㅋㅋ

**Comment by conductor-tutti** [comment]
@ohtangza @alwayssayyes @JuneSeok 다들 대강이라도 훑어 보았나요~

**Comment by ohtangza** [comment]
저는 오늘 미국으로 일주일간 출장을 가서, 비행기에서 보겠습니다 :)

On Sun, Oct 5, 2014 at 12:21 AM, Seulkiming notifications@github.com
wrote:

> 대답이 없네요?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/conductor-tutti/tutti/issues/11#issuecomment-57908644
> .

## 

_Jeungmin Oh, HCI Researcher_
_'The person what I can do and what I can't do'_

**Comment by ghost** [comment]
네 저도 해보고 있습니당~~ 탱자님 부럽습니다 미국으로 출장!

**Comment by conductor-tutti** [comment]
앞으로는 딱히 어디까지 읽자 / 어디까지 해보자고 말하지 않을게요. Collaborating 부분까지만 잘 이해했어도 GitHub 쓰는 것이 상당히 수월해졌을 것이라고 생각합니다. 그 다음은 각자 사용하면서 필요한 부분들을 찾아서 실력을 늘려 봅시다.
