### ISSUE TITLE
[musician_new] '세부전공', '시, 군, 구' select 요소 기본 값이 이상합니다.

### ISSUE THREAD

**Issue by conductor-tutti** [conductor-tutti/tutti#13]
한 번 '전공분야', '거주지역' select 요소들에서 변화가 일어나고 나면
'세부전공', '시, 군, 구' select 요소들의 기본값이 '전공분야', '거주지역'의 기본값으로 세팅됩니다.
왜그러죠? 말이 이상하네. 테스트 한 번 해보세요.

**Comment by conductor-tutti** [comment]
이거 외에도... 좀 여러가지로 이 부분이 이상하네요.. 나중에 좀 잡아야 할듯;;

**Comment by ohtangza** [comment]
무슨 말이죠?

2014-10-03 11:49 GMT+09:00 Seulkiming notifications@github.com:

> 이거 외에도... 좀 여러가지로 이 부분이 이상하네요.. 나중에 좀 잡아야 할듯;;
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/conductor-tutti/tutti/issues/13#issuecomment-57744195
> .

## 

Jeungmin Oh, Ph.D Student,
Department of Knowledge Service Engineering, KAIST
+82 - 10 - 2711 - 1357

**Comment by conductor-tutti** [comment]
말로 표현이 어려운데,
전공분야에서 뭔가를 한 번 선택하고 나면
세부전공에 클래식, 국악이 추가됩니다.
(세부전공 select 요소가 전공분야 select 요소의 default값을 갖게 됨)

동일한 현상이 지역 선택할 때도 나타납니다.

**Comment by ohtangza** [comment]
음...저도 한번 살펴봐야겠군요. Ajax 문제일지...

**Comment by conductor-tutti** [comment]
ajax문제 해결.
