### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by JuneSeok** [conductor-tutti/tutti#15]
controller.py에서
# Get category id (upper)

```
            category_query = Category.query.filter(Category.id == musician.category_id)
            category = category_query.first()
            category_upper_query = Category.query.filter(Category.id == category.upper_id)
            category_upper = category_upper_query.first()
            musician.category_upper_id = category_upper.id
```

이 부분에서 Attribute error가 납니다.

구글 콘솔에서는 
category_upper_query = Category.query.filter(Category.id == category.upper_id)
AttributeError: 'NoneType' object has no attribute 'upper_id'

이런식으로 에러가 나오는데 이게 되다가 안되다가 합니다.
정확한 분석과 문제 해결이 필요합니다.

**Comment by ohtangza** [comment]
Category_upper_id에 무슨 값이 있나 확인해보세요. 쿼리의 결과값이 0이어서 발생한 것 같습니다.

**Comment by conductor-tutti** [comment]
..는 갑자기 아무 짓도 안했는데 해결이 됬다고 하네요. 무슨 일이죠?
