### ISSUE TITLE
Ajax

### ISSUE THREAD

**Issue by JuneSeok** [conductor-tutti/tutti#16]
ajax를 이용해서 데이터 삭제를 만들었는데
한 번 작동하고는 작동이 안됩니다.
ex) 
한양대
한양대대학원

한양대학원 삭제(o)
한양대 삭제 (x)
한양대학원을 삭제하고 바로 한양대를 삭제하려고 하면 삭제가 되지 않습니다.
어떤 문제일까요
구글링 한 결과로는
e.preventDefault(); 를 넣으면 된다고 하던데
넣으니까 등록은 여러번 되는데 삭제가 안됩니다
이거 해결하고 푸쉬할려고 아직 안햇습니다.
http://tutti-alpha-juneseok.appspot.com/

**Comment by JuneSeok** [comment]
http://pastebin.com/Pz7WPAzB
코드입니당 ㅋㅋㅋ

**Comment by conductor-tutti** [comment]
확인해볼게요. 요새 저도 통 ajax쪽을 생각 안해서.. ㅡ.ㅡ

**Comment by conductor-tutti** [comment]
이 부분을 아예 제가 전달했던 의도와 다르게 짜버렸지요..
새로 짜고 있을테니, 이 이슈는 닫겠습니다 ㅎㅎ
