### ISSUE TITLE
[controllers.py] Repetitve codes should be a procedure

### ISSUE THREAD

**Issue by conductor-tutti** [conductor-tutti/tutti#17]
인덱스에서 뮤지션을 fetch하는 방식이나, 카테고리별로 뮤지션을 fetch하는 방식이나 거의 비슷한 부분이 많습니다.
반복되는 코드가 많으니, repetitive한 부분들을 procedure로 분리해서 사용하면 어떨까 하는 생각이 드는데요.

**Comment by ohtangza** [comment]
​DB에서 뮤지션을 fetch 하는 코드​ 자체가 중복되는건가요?

photo_url 등을 가져오는 부분이 중복되는 것이라면 추상화 하는 것도 괜찮을 것 같습니다.

2014-10-08 15:36 GMT+09:00 Seulkiming notifications@github.com:

> 인덱스에서 뮤지션을 fetch하는 방식이나, 카테고리별로 뮤지션을 fetch하는 방식이나 거의 비슷한 부분이 많습니다.
> 반복되는 코드가 많으니, repetitive한 부분들을 procedure로 분리해서 사용하면 어떨까 하는 생각이 드는데요.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/conductor-tutti/tutti/issues/17.

## 

Jeungmin Oh, Ph.D Student,
Department of Knowledge Service Engineering, KAIST
+82 - 10 - 2711 - 1357

**Comment by conductor-tutti** [comment]
This issue is closed due to a reason: it is not an urgent problem
