### ISSUE TITLE
쿼리 날리는 부분과 결과를 가져오는 부분을 왜 분리합니까?

### ISSUE THREAD

**Issue by conductor-tutti** [conductor-tutti/tutti#18]
@ohtangza 님이 이런 식으로 코드를 작성하셨는데요.
그 이유가 무엇입니까?

예컨대
musician_query = Musician.query.filter(Musician.user_id == user_id)
musician = musician_query.first()

이런 식으로요.
이것의 증명된 장점이 있나요?
보다보니 오히려 좀 번잡하다는 생각이 듭니다.

**Comment by ohtangza** [comment]
저걸 한줄로 쓰지 않고 두줄로 쓴 이유를 묻는건가요?

**Comment by conductor-tutti** [comment]
네.

**Comment by ohtangza** [comment]
음 이렇게 쓴 이유에 대해서 설명하자면... 주로 코드의 가독성 때문입니다.

[1] 코드를 읽다보니 Query object와 Data object(Query select의 리턴값으로부터 나오는 객체. Class 이름은 다를 수 있음)이 구분이 되지 않는 듯 하여, 이렇게 짰습니다. Query object가 줄줄줄 limit() filter_by() 등의 메소드로 체이닝이 될 수 있는데 각각의 리턴값은 all()과 first()와는 다른 객체니까요. 

예)
Musician.query.filter(~).filter(~) => query 객체
Musician.query.filter(~).limitby(~) => query 객체
Musician.query.all( ) => data 객체
Musician.query.filter~().first() => data 객체

Chaining이 여러가지 일어나고, 그 결과물에 대해서 멤버함수를 호출할 때는 라인을 분리하는데 통상 가독성에 더 도움이 됩니다. 저 같은 경우에 Flask를 잘 모르는 상태에서 위와 같이 라인이 2개로 분리가 되어 있으면, 플라스크가 Chaining을 통해서 쿼리를 생성한 다음에, Select는 first() 또는 all() 를 써서 마지막에 따로 한다는 개념을 문서를 보지 않고도 알 수 있습니다.

그러나 사실 능숙한 사람이 정확히 이해하고 쓴다면 전자나 후자나 크게 헷갈릴 염려는 없습니다.

[2] 통상의 경우, 변수를 추가하여 다른 기능을 하는 두 라인은 구분을 하는게 더 가독성이 좋습니다. 변수의 존재자체가 1)에서 이야기한 것처럼 문법적인 또는 중간단계에서의 데이터의 의미를 알려주기도 하고, 한줄에 쑤셔 넣는 방식은 대부분 가독성을 현저하게 떠어뜨립니다.

예) 어제 @JuneSeok 씨가 짜던 코드와 비슷한 상황입니다. (뮤지션 수정에서 여러 항목을 입력가능한 input 태그를 동적으로 추가하는 경우,  이벤트 핸들러 내의 코드 중에서...

(나쁜 예)
$('.where_input_tag_is_added').append('<input value=' + $('#input_education')+ '/>');

(좋은 예)
var what_user_entered = $('#input_education');
$('.where_input_tag_is_added').append('<input value=' + what_user_entered + '/>');

이렇게 씀으로서 input 태그의 value 안에 들어가는 놈이 도대체 정체가 무엇인지를 더 정확히 알 수 있는 것이지요.

물론 내가보기에는 워낙 간단한데 저걸 구지 두줄로 써야되냐라고 하면서 해당 로직의 '복잡성의 정도'에 대한 논의로 반박이 가능합니다만... 일반적인 상황에서는 제가 알기로는 이렇습니다.

(참고)
http://dsmoon.tistory.com/entry/%EC%A2%8B%EC%9D%80-%EC%BD%94%EB%93%9C-%ED%98%95%EC%8B%9D%EC%9D%B4%EB%9E%80 (5번 정도의 상황이겠네요.)

**Comment by ohtangza** [comment]
Issue closed?

**Comment by conductor-tutti** [comment]
NOT YET AS IT IS

**Comment by ohtangza** [comment]
What is the remaining problem?

On Fri, Oct 10, 2014 at 4:46 PM, Seulkiming notifications@github.com
wrote:

> NOT YET AS IT IS
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/conductor-tutti/tutti/issues/18#issuecomment-58622820
> .

## 

_Jeungmin Oh, HCI Researcher_
_'The person what I can do and what I can't do'_
