### ISSUE TITLE
getlist가 안됩니다

### ISSUE THREAD

**Issue by JuneSeok** [conductor-tutti/tutti#19]
cgi에서 getlist 함수를 이용해서 name = "education_data"인 녀석들을 넣으려는데 
들어가지가 않습니다 ㅜㅜ

**Comment by conductor-tutti** [comment]
참고
http://stackoverflow.com/questions/11817182/uploading-multiple-files-with-flask
http://nullege.com/codes/search/flask.request.form.getlist

**Comment by conductor-tutti** [comment]
뭔가.. 왜 해결됬는지 아직 명확하지 않아서.. 흠... 흠... (끙끙)

**Comment by JuneSeok** [comment]
해결 완료
-요약
request.form.getlist("name")
이런식으로 하면 name이 같은 것들이 차례대로 들어있는 list가 return됩니다

-예시
education_data = request.form.getlist("edu_data")
이렇게 하면
education_data라는 var에 edu_data라는 이름을 가진
input 들이 들어있는 list가 저장 됩니다.
