### ISSUE TITLE
Discussion on FIELD(major_id) in TABLE(musician)

### ISSUE THREAD

**Issue by ohtangza** [conductor-tutti/tutti#2]
현재 musician 테이블에...

category_id와 location_id가 있는데 이에 대한 upper_id를 가지고 있는 정보가 없어서, 프로필 수정 페이지를 짜는데 조금 어려움이 있었습니다.
(쿼리를 각 필드마다 1번씩 더 써서 해결함)

최근 commit에서 major_id를 추가한 것으로 보이는데, "만약" 필드를 추가하여 관리를 조금 더 쉽게 하려는 목표가 설정되어 있다면.....

제 생각에는 기존에 있는 legacy 코드와의 네이밍의 직관성을 위해서 category_upper_id, location_upper_id를 사용하는 것을 권장합니다. (원래는 category_parent_id, location_parent_id도 괜찮은데, 이미 category와 location 테이블에서 upper라는 키워드를 사용했으므로...)

이에 대한 의견은 댓글로 남겨주시면 감사드리겠습니다.

개인적으로는 프로토타이핑 단계에서는, 쿼리 효율성은 어느정도는 무시해도 되므로 프로필 수정 페이지가 구현이 된 현재, "지금 당장" 구지 필드를 추가할 필요는 없어 보입니다.

**Comment by conductor-tutti** [comment]
고려해 보겠습니다. @JuneSeok @alwayssayyes

**Comment by conductor-tutti** [comment]
category_upper_id = db.Column(db.Integer, db.ForeignKey("category.id"))
location_upper_id = db.Column(db.Integer, db.ForeignKey("location.id"))

해결이 되었습니다.

**Comment by ohtangza** [comment]
수고하셨습니다.

On Wed, Oct 8, 2014 at 12:34 AM, Seulkiming notifications@github.com
wrote:

> category_upper_id = db.Column(db.Integer, db.ForeignKey("category.id"))
> location_upper_id = db.Column(db.Integer, db.ForeignKey("location.id"))
> 
> 해결이 되었습니다.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/conductor-tutti/tutti/issues/2#issuecomment-58204205.

## 

_Jeungmin Oh, HCI Researcher_
_'The person what I can do and what I can't do'_
