### ISSUE TITLE
GitHub merging vs. rebasing

### ISSUE THREAD

**Issue by conductor-tutti** [conductor-tutti/tutti#20]
@alwayssayyes @JuneSeok 

우리가 지난 밤에 회의 겸 잡담을 하다가, merge와 rebase에 대해 알아보았죠.
알아보다가 서로 헷갈려서, 제가 정리해서 다시 알려드리겠다고 말씀드렸습니다.
여러분은 이미 Collaborating 부분까지 읽었기 때문에, 이미 merge 개념은 잘 알고 있으리라 생각합니다(https://www.atlassian.com/git/tutorials/using-branches/git-merge).

아래 정리 내용은 여러분에게 늘 참고하라고 말씀드리는 문서인
atlassian에서 작성한 GitHub 튜토리얼을 읽고 정리해보았으며,
merge와 rebase를 비교하는 내용은 본 문서의 Advanced Tips 두 번째 항목에 있습니다.
(https://www.atlassian.com/git/tutorials/merging-vs-rebasing)

제가 직업 문서를 해석, 의역하며 정리한 내용이며
위 문서의 상위 부분, 정확히 The Golden Rule of Rebasing 윗 부분까지만 정리한 내용입니다.
원본 문서와 함께 보면서 나름의 의미를 마음속에서 더 굳히길 바랍니다.
제가 이해한 내용에 태클 걸어도 아주 좋습니다.

[ Rebase vs. Merge ]

git rebase 명령어는 초보자들이 피해야 할 ‘마법의 Git 주술’ 이라고들 하죠(개념이 초보자들이 이해하기엔 좀 복잡성이 있어서). 하지만 잘 신경써서 쓰기만 한다면, 협업중인 팀에게 아주 유용하답니다. 이 글에서는 git rebase와 git merge를 비교하고, 어떤 상황에서 rebasing이 이루어질 수 있는지에 대해 서술하겠습니다.

[ 개념 짚고 가기 ]

git rebase에 대해 가장 처음으로 알아야 할 점이 있습니다. git merge로 해결할 수 있는 문제는, git rebase로도 해결할 수 있다는 것이죠.
이 두 명령어들은 모두 한 branch를 다른 branch에 통합하기 위해 설계된 명령어거든요. 단, 그 ‘해결하는 방식’이 매우 다릅니다.

상황을 하나 가정해보죠. 당신이 feature라는 branch에서 어떤 새로운 기능을 개발하기 시작했고, 곧이어 당신의 동료가 여러 번의 commit을 거친 뒤 master를 업데이트 한 상황이라고 생각해봅시다.
이렇게 되면 여러분이 평소에 GitHub을 쓰면서 늘 겪는 상황인, 작업 내역이 두 갈래가 된 상황(forked history)이 되겠지요.(master와 feature branch 두 갈래. 그림 참고: https://www.atlassian.com/git/images/tutorials/advanced/merging-vs-rebasing/01.svg).

또, 당신의 동료가 master에 commit한 내용들은 당신이 feature branch에서 개발 중이던 기능과 상당히 관계가 깊다(relevant)고 생각해 봅시다. 이 때 master에 있는 동료의 commit을 당신의 feature branch에 통합하고자 할 때, 두 가지 방법을 생각해볼 수 있습니다. 바로 merge하느냐, rebase하느냐이죠.

[ Merge 하는 경우 ]

master를 feature branch로 병합하는 아주 쉬운 방법은 merge하는 겁니다. 이렇게 하면 되지요:

git checkout feature
git merge master

그냥 한 줄로 쓸 수도 있습니다:

git merge master feature

이렇게 merge를 하게 되면, feature branch에 새로운 ‘merge commit’이 생성됩니다. 이 ‘merge commit’은 아까 두 갈래(forked history)로 나뉘어져 있던 작업 내역들을 하나로 묶어주게 됩니다(그림 참고: https://www.atlassian.com/git/images/tutorials/advanced/merging-vs-rebasing/02.svg).

merge하는 것은, 무언가를 파괴하지 않는(non-destructive) 명령이기 때문에 좋은 점이 있습니다. 존재하는 branch들에 아무런 변동 사항을 주지 않지요. 이렇게 merge 명령어를 쓰면, 여러분이 rebase 명령어를 사용하며 만날 가능성이 있는 여러 가지 어려운 상황을 피하게 해줍니다(밑에서 더 얘기해 줄게요).

이렇게 좋은 점도 있긴 하지만, non-destructive 하다는 것은 또한 당신이 변경사항을 병합할 때 마다 feature branch와 별 관계가 없는 ‘merge commit’이 생긴다는 것을 의미합니다. 만약에 master에서 굉장히 활발하게 commit이 이루어지고 있다면, 당신이 열심히 개발중인 feature branch는 master와 merge 할 때마다 쌓이는 ‘merge commit’ 때문에 무진장 더러워질 수가 있겠죠.

물론, git log 옵션을 좀 건드려서 이렇게 ‘더러워지는’ 문제를 해결해볼 수도 있습니다만, 당신이 아닌 다른 개발자가 작업 내역을 볼 때 매우 복잡하다고 느낄 수가 있습니다.

[ Rebase 하는 경우 ]
*rebase: 타동사. <물가 지수 따위에> 새로운 평가[산정] 기준을 설정하다. 

merge와는 또 다른 방법으로, feature branch를 master 위에(onto) rebase할 수도 있습니다. 이렇게:

git checkout feature
git rebase master

이렇게 하면 master의 새로운 commit 내역들을 feature branch의 commit들과 효과적으로 통합하면서, feature branch가 통째로 master의 상위(tip)로 이동하게 됩니다.

그니까, 아까 merge할 때는 그 어떤 branch에도 변화가 일어나지 않고, merge commit 만을 계속 쌓아 왔지요. 하지만 rebase를 하면, 원래 branch에 존재하던 각각의 commit마다 새로운 commit을 만들면서 개발 내역을 아예 다시 쓰는(re-write)겁니다(그림을 봐야 이해 갈거임. https://www.atlassian.com/git/images/tutorials/advanced/merging-vs-rebasing/03.svg 참고).

rebase하는 것의 가장 큰 장점은, 작업 내역이 훨씬 깔끔하게 남는다는 점입니다.
일단, git merge함으로써 생기는 불필요한 merge commit들이 없으니까요!
두 번째로는, 위에 그림에서 보았듯이, 작업 내역이 완벽하게 일렬로 정리될 수 있다는 점입니다(linear project history).

이렇게 정리가 잘 되있으면, git log나 git bisect, gitk 과 같은 명령어를 사용하면서 당신의 작업 내역들을 훨씬 쉽게 살펴보는 것이 가능하죠.

그러나, 이렇게 쓰여진 commit 내역에는 두 가지의 대립되는 균형 관계(trade-off)가 있습니다: 안전성과 추적 가능성이죠.
만약 당신이 Golden Rule of Rebasing(https://www.atlassian.com/git/tutorials/merging-vs-rebasing/conceptual-overview#the-golden-rule-of-rebasing, 읽어보세요)을 따르지 않는다면, 위처럼 작업 내역을 다시 쓰는 것(re-write)는 잠재적으로 협업에 큰 문제를 야기할 수도 있습니다.

그리고, 뭐 아주 중요한 것은 아닙니다만, rebase를 하게 되면 merge commit이 제공해주는 작업 정황(context)에 대한 정보를 잃게 됩니다. 그니까, 언제 branch가 서로 통합되었는지 알 수가 없다는 점이죠.

[ Interactive Rebasing ]

Interactive rebasing은 새로운 branch에 이주할 commit들을 직접 변경할 수 있도록 해줍니다.
자동 rebase보다 훨씬 강력한 기능인데요. 왜냐면, branch의 commit 내역을 모두 컨트롤 할 수 있도록 해주기 때문입니다(이건 직접 해봐야 느낄거임).
일반적으로 Interactive rebasing은, master에 feature branch를 완전히 합치기 전에, 보기 싫은 작업 내역을 깔끔하게 정리하는 데에 많이 쓰입니다.

Interactive rebasing을 하려면, git rebase 명령어에 옵션을 하나 추가하면 됩니다. 이렇게:

git checkout feature
git rebase –i master

이렇게 하면, master로 이동할 모든 commit들을 보여주는 텍스트 편집기가 하나 뜹니다. 이런식으로:

pick 33d5b7a Message for commit #1
pick 9480b3d Message for commit #2
pick 5c67e61 Message for commit #3

이렇게 나열된 모습은, rebase가 완료되고 난 뒤 branch가 어떻게 보일지를 정확하게 나타내줍니다. 

pick 명령어를 바꾸거나, 각각의 commit들의 순서를 바꿈으로써, branch의 작업 내역들을 당신이 원하는 대로 마음껏 깔끔하게 바꿀 수가 있죠. 예를 들어서, 저 두 번째 commit이 첫 번째 commit에 존재하는 작은 문제를 해결하는 내용이라면, 이 두 commit을 fixup 명령어를 사용해서 하나로 압축해버릴 수 있습니다. 

이렇게 정리를 하고! 저장하고! 파일을 닫으면, Git이 당신이 정리해둔 대로 알아서 잘 rebase 처리를 하고, 다음 그림과 같은 작업 내역을 갖게 됩니다(https://www.atlassian.com/git/images/tutorials/advanced/merging-vs-rebasing/04.svg).
이렇게 별 중요하지 않은 commit들을 없애버리는 일은, 당신의 작업 내역을 더 잘 이해하는데 도움을 줍니다. 이런건 git merge가 할 수 없는 일이죠.

**Comment by conductor-tutti** [comment]
Collaborating에 https://www.atlassian.com/git/tutorials/comparing-workflows 이 부분을 다시 한 번 정독해보세요. 이해가 더 잘 될 것입니다. 만약 Collaborating 파트를 전혀 제대로 읽어보지 않았다면.. 당신은 잠재적인 GitHub 킬러 입니다.. 책임 못짐..

**Comment by ghost** [comment]
정리해줘서 고맙습니디♥

**Comment by ohtangza** [comment]
읽고 정리된 거 보면 나는 Git master
안 읽고 정리된 더 보면 난 Git killer

**Comment by conductor-tutti** [comment]
@JuneSeok 읽고 이슈 닫아주세요. (부들부들)

**Comment by JuneSeok** [comment]
넵 알겠습니당 누나 수고 하셨어요!!
