### ISSUE TITLE
Backup file?

### ISSUE THREAD

**Issue by rishubil** [conductor-tutti/tutti#21]
https://github.com/conductor-tutti/tutti/blob/e6d7cd86d4df210756ab439f336e36520dbcf5da/app/templates/musician/musician_new_backup.html

e6d7cd86d 내용 중 `musician_new_backup.html` 라는 파일이 있는데 이 파일은 `musician_new.html`의 이전 버전을 임시로 보관하는 파일인가요?

만약 그렇다면, 이 파일 대신 git의 이전 버전을 보는 기능으로 대체하는 것이 좋지 않을까요? :wink:

**Comment by conductor-tutti** [comment]
하이루. 아뇨. 설마 GitHub 쓰면서 그런 짓을. ㅋㅋㅋ 아마 예전에 뭔가 디자인 바뀌는 것 때문에 임시로 잠시 만들었던 파일 같네요. 현재는 존재하지 않는 파일입니다. Juneseok_branch가 갖고 있던 예전 commit history를 통해 다시 살아난 듯. -_-;;

**Comment by rishubil** [comment]
그렇군요... 그럼 다음 커밋에 파일 제거해주시고 이슈 닫아주세욥.

**Comment by conductor-tutti** [comment]
@JuneSeok 의심스러운 파일이 있을 때는 얘기 하세염.

**Comment by JuneSeok** [comment]
이건 제가 따로 작업 할 때 보고 하려고 따로 만든 거 였는데 제가 안지웠네용 ㅋㅋㅋ
필요없는 파일입니다.
