### ISSUE TITLE
a lot of names will be changed(when dealing with category, location data)

### ISSUE THREAD

**Issue by conductor-tutti** [conductor-tutti/tutti#22]
현재 변수명, 함수명 등이 'sido', 'sigungu', 'locationsido', 'category', 'major' 등으로 조금 번잡하게 되어있는데,
DB스키마가 바뀜에 따라 이런 이름들을 더 직관적이고 / 알아보기 쉽게 바꾸려고 합니다.
제가 보다가 헷갈려서 죽겠네요.

[전공분야]
category -> upperCategory
[세부전공]
major -> subCategory

[활동지역(시, 도)]
location 혹은 sido(일관성 없는 상태) -> upperLocation
[세부활동지역(시, 군, 구)]
location_detail, sigungu(마찬가지) -> subLocation

요런 식으로 바꾸고 commit 내역을 이 이슈에 연결해 두겠습니다.
변수명좀 예쁘게 지읍시다. ㅠㅠ

**Comment by JuneSeok** [comment]
넵 알겠습니당

**Comment by conductor-tutti** [comment]
FIXED!
