### ISSUE TITLE
education_delete() and repertoire_delete() weren't completely modified

### ISSUE THREAD

**Issue by conductor-tutti** [conductor-tutti/tutti#23]
이전 페어프로그래밍 시간에
musician_new() 부분에서 ajax로 통신하지 않아도 상관 없다는 결론이 났었지요. 안타깝게도..
(이전에는 등록, 삭제가 모두 ajax로 처리되어 있었고, user.is_musician == 0 인 경우 musician_new.html에 접근하기만 해도 바로 user.is_musicain == 1 이 되어버리는 등의 문제가 있었음)

그런데 아직도 delete 하는 부분들은 수정이 안되어 있군요(musician_new.js).
사실 이제 삭제하는 부분도 ajax가 필요가 없잖아요.
까먹고 수정을 안 한 것이 맞지요? 제가 임의로 수정 합니다? ㅋㅋ

input fields만 .js 파일에서 추가/삭제를 핸들링 해주면 될 뿐이지
정말 '삭제' 버튼을 누르자 마자 바로 DB에서 삭제될 필요는 딱히 없으니까요.
@JuneSeok

**Comment by JuneSeok** [comment]
넵 알겟습니다!!
