### ISSUE TITLE
[musician_new.js] .remove() is not working

### ISSUE THREAD

**Issue by conductor-tutti** [conductor-tutti/tutti#24]
간단한 코드입니다. 77줄의 .remove() 가 동작하지 않는데요.
왜 그럴까요?

61줄 ~ 74줄에서 만든 .newEducationRow를 찾지 못하는 걸까요?

**Comment by conductor-tutti** [comment]
아, 그런데 저게 동작을 한다 해도.. 모든 newEducationRow를 지워버리겠구나. 흠 문제가 있네요. 혼자 다시 짜고 오겠습니다. 애초에 저렇게 단순하게 .remove() 하겠다고 생각한 것 자체가 경기도 오산이군요.

**Comment by ohtangza** [comment]
레이블이 좋군요.

**Comment by JuneSeok** [comment]
id를 이용해서 하나씩 지워야 하는데 id를 먹이기가 힘들군요 ㅜㅜ

**Comment by conductor-tutti** [comment]
ㅋㅋ 아뇨 안그래도 됩니다.

**Comment by JuneSeok** [comment]
ㅋㅋㅋㅋㅋ누나한테 많이 배워야겟네요
2014. 10. 13. 오후 4:39에 "Seulkiming" notifications@github.com님이 작성:

**Comment by conductor-tutti** [comment]
http://www.lessoncup.com/2014/01/jquery-dynamically-add-input-fields.html

이런 dynamic input fields는 굉장히 흔하니까... 예시는 엄청 많은데, 그중 이게 제일 맘에들고 기존 기획 방향이랑 거의 비슷하더군요. 이거 참고했습니다.

**Comment by JuneSeok** [comment]
오오 굿이네요
최고!!

**Comment by ghost** [comment]
오오 멋져요!

**Comment by conductor-tutti** [comment]
잘 안 됨.

**Comment by conductor-tutti** [comment]
지우는게 영 잘 안되서 짜증이 머리 끝 까지 나려고 했는데.. 간단한 문제였습니다.
.parent()와 .parents()의 차이.

click 이벤트는 들어가는데 자꾸 삭제가 안되서.. 도대체 왜 그럴까 생각해보니, parent를 찾아서 지우는 부분에서 뭘 지워야 될지 모르겠나부다. 하는 생각이 들긴 했는데..
.parent()와 .parents() 때문인 줄은 몰랐네요. 문서 보고 앎. 문서 보고나서도 .parents()에 넘겨주는 인자 때문에 좀 헤맴. ㅋㅋ

그냥 아무 selector 정보 없이 parents를 지우면, 문서가 통째로 걍 지워집니다.

http://api.jquery.com/parents/

**Comment by ghost** [comment]
고생했어요!!
