### ISSUE TITLE
[javaScript] better solution for appending long HTML, and dynamic attributes

### ISSUE THREAD

**Issue by conductor-tutti** [conductor-tutti/tutti#26]
자바스크립트에서 HTML요소를 추가할 일이 있을 때..
기존에는 따옴표, 플러스 기호 등을 이용해서 다소 번잡하게(제 기준이긴 하지만) 추가했습니다.
append할 코드가 엄청 짧으면 괜찮은데, 길 경우에는 헷갈리기 시작합니다.

이럴 때 backslash를 이용해서 여러 줄을 비교적 쉽게 입력할 수도 있습니다.
그런데 전 이것도 짜증이 나서.. 이렇게 해보았습니다.

**Comment by conductor-tutti** [comment]
http://backbonetutorials.com/what-is-a-view/
Javascript Framework 중에서 전세계 1, 2위 정도 하는 Backbone.js 라는 데서 템플릿을 연결된 코드처럼 사용합니다.  다만 replace를 쓰지는 않고, var template = _.template( $("#search_template").html(), {} ); 와 같은 형식으로 2번째 인자에 dictinoary를 줘서 여러가지 인자도 받을 수 있게 디자인 되어 있습니다(경쟁 라이브러리는 구글의 Angular.js 정도 됨). 

이 template 함수가 어떻게 동작하는지 찾아서 공부하는 것도 재미있을 것 같군요. (저는 모름)

**Comment by JuneSeok** [comment]
와 이건 정말 획기적이네요!!!!!!!!!
방법을 찾아보지도 않고 그냥 무식하게 
한 제가 부끄럽네요 ㅜㅜ
누나짱

**Comment by conductor-tutti** [comment]
이해했다니 다행!
