### ISSUE TITLE
[musician_new.js] formValidate() without alert()

### ISSUE THREAD

**Issue by conductor-tutti** [conductor-tutti/tutti#28]
SAVING_STATICS 브랜치에 있는 musician_new.js 파일 기준으로 이야기 합니다.
현재 formValidate() 함수는 validate 해야하는 폼 요소들을 모두 돌며 alert() 창을 띄우고, focus()하고 있는데요.
이런 방식 보다 화면 전환이 덜 일어나고, 더 간단하면서, 예쁘게 하고 싶네요.

예를들어 validate 결과가 false인 폼 요소를 focus() 하면서, 그 해당 폼 요소에 뭐 말풍선을 붙여놓는다던가..

**Comment by JuneSeok** [comment]
얼른 시험 치고 코딩에 참여 있도록 하겠습니다!
이것만 봐서는 약간 이해가 안되네요 ㅋㅋ
