### ISSUE TITLE
Add FIELD[video_url] in TABLE[musician]

### ISSUE THREAD

**Issue by ohtangza** [conductor-tutti/tutti#3]
musician_new.html에 동영상을 올릴 수 있는 필드가 추가되어 있는데, 이와 연관되어 있는 Controller와 profile.html은 구현이 되지 않은 것으로 보입니다.
(제가 잘 못 알고 있는 것이라면, 지적 해주세요.)

**Comment by ohtangza** [comment]
한 분이 Controller 작업을 하면, @conductor-tutti  가 View 작업을 하는 것도 괜찮아 보입니다. 의견 주세요.

**Comment by conductor-tutti** [comment]
네. Column도 없고, controller에서 처리해주고 있지도 않습니다.
현재는 @ohtangza 님이 임의로 추가한 비디오 URL만 들어가 있네요.
작업 완료되면 이슈 닫겠습니다.

**Comment by ohtangza** [comment]
넵.
