### ISSUE TITLE
GAE 서버 쓸 때, 각자 Development 버전 달리 해서 사용하기

### ISSUE THREAD

**Issue by ohtangza** [conductor-tutti/tutti#4]
app.yaml에 보면 version이라는 필드가 있습니다.

이 필드를 달리 하면, 서버에서도 여러가지 버전의 소스를 돌릴 수 있습니다.

개인적으로

1: Up-to-date public version (공용)
2: @conductor-tutti 
3: @JuneSeok 
4: @alwayssayyes 
5: @ohtangza

이렇게 쓰는 것이 좋을 것 같습니다.

지금이야 개발중이라서, 갑자기 접속이 안되어도 괜찮지만 나중에 Alpha 테스트만 해도 Version1을 잘 못 건드려서 접속이 안되면 큰일 나게 됩니다.
(보통 Default 버전인 1은 http://tutti-alpha-seulki.appspot.com/로 바로 연결)

1번 이외에 각 버전에 대한 접속 주소는 

http://[VERSION].tutti-alpha-seulki.appspot.com/가 됩니다.
(저 같은 경우는 http://5.tutti-alpha-seulki.appspot.com/가 되겠죠...)

중요한 이슈이므로 확인하신 분은 코멘트에 ACK 달아주세요.

**Comment by conductor-tutti** [comment]
그렇게 하는게 좋겠네요. 저는 명시된 대로 2번 쓸게요.
다들 app.yaml 파일에서 application: tutti-alpha-seulki, version: (본인 해당 버전) 으로 바꾸십시옹.

**Comment by JuneSeok** [comment]
넵 알겟습니다. 구글 콘솔에 초대 받아서 수락햇고 저는 3번을 쓰도록 하겟습니다
2014. 10. 1. 오전 11:37에 "Jeungmin Oh" notifications@github.com님이 작성:

**Comment by ghost** [comment]
저도 확인했고 4번 쓸게여!
