### ISSUE TITLE
GAE Collaborator에 개발자들 ID 추가

### ISSUE THREAD

**Issue by ohtangza** [conductor-tutti/tutti#5]
현재 tutti.conductor@gmail.com을 공유하여 사용하고 있는데, 이렇게 하면 누가 무슨 일을 했는데 트래킹도 되지 않고 보안에 문제가 있습니다.

준석, 소영씨를 슬기씨가 Google App Engine Admin Console에서 Collaborator로 추가해주세요.

**Comment by conductor-tutti** [comment]
소영씨는 한 달간 공부 모드입니다. 준석씨만 추가합니다.

**Comment by ghost** [comment]
네~
