### ISSUE TITLE
2014 드림하이 ERICA 창업 페스티벌 지원

### ISSUE THREAD

**Issue by conductor-tutti** [conductor-tutti/tutti#7]
MVP 개발과 함께 정부지원사업, 창업관련 지업사업도 병행하려 합니다.
한양대학교 ERICA 캠퍼스에서 개최하는 창업 페스티벌 입니다.
팀원 중 제가 학생이 아니니, 소영이가 내일(2일, 목요일) 문제 없는지 학교에 물어봐 주세요.
http://ekf.hanyang.ac.kr/notice/72

**Comment by JuneSeok** [comment]
Soyeong fighting
2014. 10. 1. 오후 6:09에 "Seulkiming" notifications@github.com님이 작성:

**Comment by ghost** [comment]
네 알겠습니당^^ 화이팅!!
2014. 10. 1. 오후 6:09에 "Seulkiming" notifications@github.com님이 작성:

**Comment by ghost** [comment]
<2014 드림하이 ERICA 창업페스티벌> 자주묻는질문
1. 9. 29.   2014. 9. 30.   38   드림하이
   안녕하세요, <2014 드림하이 ERICA 창업 페스티벌> 담당자 입니다smiley

많은 분들이 페스창업페스티벌에 대한 문의전화가 많습니다. 자주묻는 질문에 대한 답변 드립니다.

*Q. 졸업생은 팀원으로 참가 불가능 한가요?

*A. 네. 국내대학(원)생 재학 또는 휴학을 증명할 수 있는 분만 참가 가능합니다.

Q. 창업아이템을 중복지원해도 괜찮나요?

A. 한 팀당 하나의 사업아이템만 가능합니다. 단, 개인이 두 팀에 해당할 경우 중복지원이 가능합니다. (두 팀으로 인정하는 경우: 동일한 개인이 양 팀의 대표를 맡지 아니하거나 두 팀 인원의 중복여부가 1/3미만으로 이뤄져야함)

Q. 타 페스티벌 또는 경진대회에서 수상을 했더라도 참가 가능할까요?

A. 수상기록이 있는 아이템의 경우  참가 불가능합니다. 단, 교내경진대회(외부 대학이 참가하지 않은) 수상작은 참가 가능합니다. 또한 수상 아이템이 기존 수상작과의 변화됐다는 점이 타당할 경우 참가 가능합니다.

Q. 서류접수는 메일로도 가능한가요?

A. 서류접수는 해당 홈페이지에 개설중인 드림하이 전용게시판에서 가능합니다. 접수기한은 2014. 10. 8(수) ~ 11. 5(수)까지 입니다.

Q. 접수양식에 스캔접수 후 진행을 하라고 하던데 사진을 찍어도 괜찮은가요?

A. 네. 사진을 찍어 편집하셔도 무방하나 사진의 화질이 나빠 식별이 힘든 경우는 반드시 스캔본을 보내주셔야 합니다.

Q. 팀명이 없어도 제출가능한가요?

A. 네 가능합니다. 대신 제출자의 성명을 기입하셔야 합니다.

Q. 본선진출팀은 총 몇팀인가요?

A. 접수결과에 따라 다를 수 있으나, 현재 18~20팀이 선발할 예정입니다.

Q. 본선발표는 어디서 어떻게 이루어지나요?

A. 한양대 ERICA캠퍼스 내 소극장에서 진행됩니다. 발표자료는 자유양식으로 진행되며 준비하시는 발표자료는 PDF로 제출하셔야 합니다. 

Q. 수상작 전시를 한다고 하는데 어떤건가요?

A. ERICA캠퍼스 내 오프라인 및 홈페이지에서 전시 예정입니다. 여러분이 진행 한 사업계획서 중 사업 아이템, 시장 현황 분석, 비즈니스 모델 정도의 내용을 전시 할 예정이므로 부담갖지 않으셔도 됩니다. 

이밖에 추후 궁금하신 점에 대해서는 지속적으로 업데이트 하도록 하겠습니다. 많은 관심 가져주셔서 감사합니다.

그럼 모두 드림하이 하세요~!

**Comment by conductor-tutti** [comment]
@alwayssayyes  답변 잘 읽었습니다. 그런데, 이렇게 내용을 그대로 긁어올 때는 중요한 부분에 표시를 해주시는 센스를 부탁합니다. 이 경우에는 '졸업생은 팀원으로 참가 불가능 한가요?' 질문과 답이겠네요. 사실상 우리 팀이 이 부분을 만족시킬 수 없다면, 다른 질문과 답변은 중요도가 떨어지니까요.

제가 별표 해놨습니다. 그럼 '드림하이'는 포기할까싶네요. 어떻게 생각?

**Comment by conductor-tutti** [comment]
의견이 없네요. 지원하지 않겠습니다.

**Comment by ghost** [comment]
지원하면 좋겠다고 생각은 했으나 팀원중 한명이 이름을 넣지 못한다면 저는 그 사람의 마음이 제일 중요하다고 생각해서 슬기가 지원하지 않을까 싶다 말하기에 잠정적으로 지원하지 않기로 모두 결정을 내렸다고 생각했네요! 오늘도 좋은하루 되세요 모두♥

**Comment by conductor-tutti** [comment]
그랬군여.
