### ISSUE TITLE
Multiple inputs in musician_new.html

### ISSUE THREAD

**Issue by conductor-tutti** [conductor-tutti/tutti#9]
하나 이상의 인풋이 들어올 수 있는 요소들이 있습니다.

1) 사진: 뮤지션은 메인에 노출될 이미지 말고도, 추가적인 프로필 사진을 여러개 올릴 수 있어야 함.
2) 학력
3) 레퍼토리
4) 동영상 주소

모델과 컨트롤러, 그리고 템플릿에 전부 변화가 일어나겠네요.
DEADLINE: 10.3(fri)

**Comment by ohtangza** [comment]
이런 필드들은 아마, 테이블을 분리해야할 가능성이 높습니다. (뮤지션에 붙지 않을까 싶네요.)

참고하세요~

2014-10-01 19:06 GMT+09:00 Seulkiming notifications@github.com:

> 하나 이상의 인풋이 들어올 수 있는 요소들이 있습니다.
> 
> 1) 사진: 뮤지션은 메인에 노출될 이미지 말고도, 추가적인 프로필 사진을 여러개 올릴 수 있어야 함.
> 2) 학력
> 3) 레퍼토리
> 4) 동영상 주소
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/conductor-tutti/tutti/issues/9.

## 

Jeungmin Oh, Ph.D Student,
Department of Knowledge Service Engineering, KAIST
+82 - 10 - 2711 - 1357

**Comment by ghost** [comment]
아 테이블을 분리해야하는군요!

**Comment by JuneSeok** [comment]
네 테이블 분리해서 Foreign Key를 주워서 관리하겠습니다!!

**Comment by conductor-tutti** [comment]
@JuneSeok  Foreign Key를 '줍는다'는게 재밌다! ㅋㅋ 신선하다!
